
Mappings:
  regionMap:
    us-east-1:
      imageId: ami-0c5bf07e510b75b11

Resources:
  saleApiEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap 
        - regionMap
        - !Ref 'AWS::Region'
        - imageId
